"""How setup talks to the person: a console today, a desktop app's windows tomorrow.
Plugins' setup steps use the same interface."""

from __future__ import annotations

from typing import Protocol


class SetupError(Exception):
    """Setup can't go on; the message says what the person should do."""


class UI(Protocol):
    def step(self, title: str) -> None: ...
    def done(self, text: str) -> None: ...
    def info(self, text: str) -> None: ...
    def warn(self, text: str) -> None: ...
    def ask(self, prompt: str) -> str: ...
    def secret(self, prompt: str) -> str: ...
    def confirm(self, prompt: str, default: bool = True) -> bool: ...
